# Generated by Django 6.0.2 on 2026-04-14 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_coordinated_funder'),
        ('activities', '0001_initial'),
        ('masters', '0003_activitycategory_activitysubcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('report', 'Technical Report'), ('proposal', 'Proposal Document'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('other', 'Other Document')], default='report', max_length=50)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('other', 'Other')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('is_latest', models.BooleanField(default=True, help_text='Indicates if this is the latest version')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for version control')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Activity Assignment'), ('status_change', 'Status Change'), ('due_date_alert', 'Due Date Alert'), ('update', 'Activity Update'), ('comment', 'New Comment')], default='update', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_assignment', models.BooleanField(default=True)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_due_date_alert', models.BooleanField(default=True)),
                ('notify_on_activity_update', models.BooleanField(default=True)),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('email_immediately', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=False)),
                ('email_weekly_digest', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Don't send emails before this time", null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text="Don't send emails after this time", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-year', 'activity_id']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='funder',
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_delivery_date',
            field=models.DateField(blank=True, help_text='Actual delivery date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_order_date',
            field=models.DateField(blank=True, help_text='Actual order placement date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_payment_date',
            field=models.DateField(blank=True, help_text='Actual payment date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_tendering_date',
            field=models.DateField(blank=True, help_text='Actual tendering completion date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='masters.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='Legacy activity categories'),
        ),
        migrations.AddField(
            model_name='activity',
            name='clusters',
            field=models.ManyToManyField(blank=True, related_name='activities', to='accounts.cluster'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='funders',
            field=models.ManyToManyField(blank=True, related_name='activities', to='masters.funder'),
        ),
        migrations.AddField(
            model_name='activity',
            name='generated_from_recurrence',
            field=models.BooleanField(default=False, help_text='True if this activity was auto-generated from a recurring template'),
        ),
        migrations.AddField(
            model_name='activity',
            name='has_partial_procurement',
            field=models.BooleanField(default=False, help_text='Auto-set to True if procurement_amount is set and < total_budget'),
        ),
        migrations.AddField(
            model_name='activity',
            name='in_procurement_plan',
            field=models.BooleanField(default=False, help_text='True if this activity is in the procurement plan'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_construction',
            field=models.BooleanField(default=False, help_text='True if this activity is a construction activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_procurement',
            field=models.BooleanField(default=False, help_text='True if this entire activity is a procurement'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Mark if this activity repeats on a schedule'),
        ),
        migrations.AddField(
            model_name='activity',
            name='order_date',
            field=models.DateField(blank=True, help_text='Planned order placement date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='parent_activity',
            field=models.ForeignKey(blank=True, help_text='If this is a recurring instance, references the template/parent activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Expected payment date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='procurement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of total budget allocated to procurement (leave blank if no procurement)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='procurement_breakdowns',
            field=models.JSONField(blank=True, help_text='Detailed breakdown of procurement items: [{type, amount, description}, ...]', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='procurement_type',
            field=models.ForeignKey(blank=True, help_text='Type of procurement', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.procurementtype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='procurement_type_old',
            field=models.CharField(blank=True, help_text='Old procurement type field (temporary during migration)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Stop generating instances after this date; leave blank for indefinite', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_interval',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Repeat every N periods (e.g., every 1 month, every 2 quarters)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annual', 'Bi-Annual (every 6 months)'), ('annual', 'Annual')], default='monthly', help_text='Pattern for recurring activities', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='masters.activitysubcategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tendering_date',
            field=models.DateField(blank=True, help_text='Planned tendering date', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='retired',
            field=models.BooleanField(default=False, help_text='True if activity has been financially retired'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_recurring'], name='activities__is_recu_2e4401_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_procurement'], name='activities__is_proc_90253d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['parent_activity'], name='activities__parent__a29af9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['recurrence_end_date'], name='activities__recurre_479564_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['year', 'planned_month'], name='activities__year_3dfddb_idx'),
        ),
        migrations.AddField(
            model_name='activityattachment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activityattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityattachment',
            index=models.Index(fields=['activity', 'is_latest'], name='activities__activit_3bf950_idx'),
        ),
        migrations.AddIndex(
            model_name='activityattachment',
            index=models.Index(fields=['document_type', 'is_deleted'], name='activities__documen_d60465_idx'),
        ),
        migrations.AddIndex(
            model_name='activityattachment',
            index=models.Index(fields=['uploaded_at'], name='activities__uploade_215748_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['activity', 'recipient'], name='activities__activit_152f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'created_at'], name='activities__status_acb1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='activities__notific_d716d8_idx'),
        ),
    ]
