# Generated by Django 6.0.1 on 2026-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_procurement_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='retired',
            field=models.BooleanField(default=False, help_text='True if activity has been financially retired'),
        ),
    ]
