# Generated by Django 6.0.1 on 2026-02-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_deleted_alter_activity_retired'),
        ('fleet', '0002_rename_notes_tripallocation_allocation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='transport_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fleet.transportrequest'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='trip_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fleet.tripallocation'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Activity Assignment'), ('status_change', 'Status Change'), ('due_date_alert', 'Due Date Alert'), ('update', 'Activity Update'), ('comment', 'New Comment'), ('transport_request_submitted', 'Transport Request Submitted'), ('transport_request_approved', 'Transport Request Approved'), ('transport_request_rejected', 'Transport Request Rejected'), ('trip_allocated', 'Trip Allocated'), ('trip_confirmed', 'Trip Confirmed'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('trip_cancelled', 'Trip Cancelled')], default='update', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['transport_request', 'recipient'], name='activities__transpo_37b905_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['trip_allocation', 'recipient'], name='activities__trip_al_1f2c45_idx'),
        ),
    ]
