# Generated by Django 6.0.1 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_activitycategory_activitysubcategory'),
        ('activities', '0012_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='masters.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='activities', to='masters.activitysubcategory'),
        ),
    ]
