# Generated by Django 6.0.1 on 2026-04-07
# No-op: categories and sub_categories are already created by 0002 on a fresh install.
# Kept in the chain for historical continuity; fake-applied on existing DBs.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_activitycategory_activitysubcategory'),
        ('activities', '0002_activityattachment_notificationlog_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[], database_operations=[]),
    ]
