# Generated by Django 6.0.3 on 2026-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Date when delivery was completed', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='order_date',
            field=models.DateField(blank=True, help_text='Date when the order was placed', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='tendering_date',
            field=models.DateField(blank=True, help_text='Date when tendering was completed', null=True),
        ),
    ]
