# Generated by Django 6.0.3 on 2026-04-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_activity_category'),
        ('masters', '0003_procurementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='procurement_status',
            field=models.ForeignKey(blank=True, help_text='Status of the procurement process', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.procurementstatus'),
        ),
    ]
