# Generated by Django 6.0.1 on 2026-04-07
# No-op: is_construction is already added by 0002 on a fresh install.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_categories_sub_categories'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[], database_operations=[]),
    ]
