# Generated by Django 6.0.1 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_categories_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_construction',
            field=models.BooleanField(default=False, help_text='True if this activity is a construction activity'),
        ),
    ]
