# Generated by Django 6.0.1 on 2026-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_is_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='in_procurement_plan',
            field=models.BooleanField(default=False, help_text='True if this activity is in the procurement plan'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text='Legacy activity categories'),
        ),
    ]
