# Generated by Django 6.0.1 on 2026-04-08 10:31
# No-op: in_procurement_plan and category (JSONField) are already handled by 0002 on a fresh install.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_activity_is_construction'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[], database_operations=[]),
    ]
