# Generated by Django 6.0.4 on 2026-04-10 10:00
# No-op: all procurement stage date fields are already added by 0002 on a fresh install.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_activity_in_procurement_plan_alter_activity_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[], database_operations=[]),
    ]
