# Generated by Django 6.0.4 on 2026-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_activity_in_procurement_plan_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='actual_delivery_date',
            field=models.DateField(blank=True, help_text='Actual delivery date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_order_date',
            field=models.DateField(blank=True, help_text='Actual order placement date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_payment_date',
            field=models.DateField(blank=True, help_text='Actual payment date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_tendering_date',
            field=models.DateField(blank=True, help_text='Actual tendering completion date', null=True),
        ),
        # delivery_date, order_date, payment_date, tendering_date already exist in the DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='activity',
                    name='delivery_date',
                    field=models.DateField(blank=True, help_text='Expected delivery date', null=True),
                ),
                migrations.AddField(
                    model_name='activity',
                    name='order_date',
                    field=models.DateField(blank=True, help_text='Planned order placement date', null=True),
                ),
                migrations.AddField(
                    model_name='activity',
                    name='payment_date',
                    field=models.DateField(blank=True, help_text='Expected payment date', null=True),
                ),
                migrations.AddField(
                    model_name='activity',
                    name='tendering_date',
                    field=models.DateField(blank=True, help_text='Planned tendering date', null=True),
                ),
            ]
        ),
    ]
