# Generated by Django 6.0.4 on 2026-04-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_procurement_stage_dates'),
    ]

    operations = [
    ]
