# Generated by Django 6.0.3 on 2026-04-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_procurementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementstatus',
            name='color_code',
            field=models.CharField(default='#64748b', help_text='Hex color code for tags (e.g. #3b82f6)', max_length=7),
        ),
    ]
