# Generated by Django 6.0.1 on 2026-02-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('masters', '0002_procurementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinated_funder',
            field=models.ForeignKey(blank=True, help_text='Funder that this Project Coordinator manages', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.funder'),
        ),
    ]
