# Generated by Django 6.0.1 on 2026-07-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_fleet_groups'),
        ('bookings', '0002_add_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department, used to prefill transport requests', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='bookings.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Job title, used to prefill transport requests', max_length=200),
        ),
    ]
