# Generated by Django 6.0.1 on 2026-02-18 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0011_activity_deleted_alter_activity_retired'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(db_index=True, help_text='Unique driver license number', max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Driver contact phone', max_length=20)),
                ('license_expiry_date', models.DateField(help_text='Driver license expiry date')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('on_leave', 'On Leave')], db_index=True, default='available', max_length=20)),
                ('assigned_location', models.CharField(blank=True, help_text='Location where driver is based', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(db_index=True, help_text='Auto-generated request identifier', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('activity_name', models.CharField(help_text='Name of the activity/trip', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of transport need')),
                ('pickup_location', models.CharField(help_text='Pickup location address', max_length=255)),
                ('destination', models.CharField(help_text='Destination address', max_length=255)),
                ('departure_datetime', models.DateTimeField(help_text='Planned departure date and time')),
                ('return_datetime', models.DateTimeField(help_text='Planned return date and time')),
                ('num_passengers', models.PositiveIntegerField(default=1, help_text='Number of passengers')),
                ('justification', models.TextField(help_text='Justification for transport request')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements (e.g., wheelchair access, equipment space)')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date/time of approval', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transport_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_activity', models.ForeignKey(blank=True, help_text='Linked implementation activity (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='activities.activity')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TripAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='allocated', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When driver confirmed this allocation', null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Driver who confirmed this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allocations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fleet.driver')),
                ('transport_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_allocation', to='fleet.transportrequest')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('trip_allocated', 'Trip Allocated'), ('driver_confirmed', 'Driver Confirmed'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('trip_cancelled', 'Trip Cancelled'), ('allocation_modified', 'Allocation Modified')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (if modification)')),
                ('new_value', models.TextField(blank=True, help_text='New value (if modification)')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('transport_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='fleet.transportrequest')),
                ('trip_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='fleet.tripallocation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_mileage', models.PositiveIntegerField(help_text='Odometer reading at start (in km)')),
                ('end_mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading at end (in km)', null=True)),
                ('distance', models.PositiveIntegerField(blank=True, editable=False, help_text='Calculated distance (end - start)', null=True)),
                ('start_datetime', models.DateTimeField(auto_now_add=True, help_text='When trip recording was started')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When trip was completed', null=True)),
                ('incident_notes', models.TextField(blank=True, help_text='Any incidents or issues during trip')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('trip_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_log', to='fleet.tripallocation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, help_text='Unique vehicle registration number', max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('truck', 'Truck'), ('minibus', 'Minibus')], default='van', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='diesel', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='available', help_text='Current availability status', max_length=20)),
                ('assigned_location', models.CharField(blank=True, help_text='Location where vehicle is based', max_length=255)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether vehicle is in service')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
                'ordering': ['registration_number'],
            },
        ),
        migrations.AddField(
            model_name='tripallocation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('tire_change', 'Tire Change'), ('oil_change', 'Oil Change'), ('other', 'Other')], default='routine', max_length=20)),
                ('service_date', models.DateField(help_text='Date service was performed')),
                ('next_due_date', models.DateField(help_text='Date next service is due')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of service in currency', max_digits=10)),
                ('service_provider', models.CharField(blank=True, help_text='Name of workshop/service provider', max_length=255)),
                ('mileage_at_service', models.PositiveIntegerField(blank=True, help_text='Vehicle mileage at time of service', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='fleet_drive_status_bfaf48_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active'], name='fleet_drive_is_acti_06067a_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status', 'is_active'], name='fleet_drive_status_fa3421_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['status'], name='fleet_trans_status_f512cd_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['requested_by'], name='fleet_trans_request_57d45e_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['departure_datetime'], name='fleet_trans_departu_92e116_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['status', 'departure_datetime'], name='fleet_trans_status_49e92a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='fleet_audit_action_8a0a87_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='fleet_audit_perform_e22070_idx'),
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['trip_allocation'], name='fleet_tripl_trip_al_438a65_idx'),
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['start_datetime'], name='fleet_tripl_start_d_c760f1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='fleet_vehic_status_f5cfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='fleet_vehic_is_acti_007c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'is_active'], name='fleet_vehic_status_9a8698_idx'),
        ),
        migrations.AddIndex(
            model_name='tripallocation',
            index=models.Index(fields=['vehicle', 'status'], name='fleet_tripa_vehicle_57e53f_idx'),
        ),
        migrations.AddIndex(
            model_name='tripallocation',
            index=models.Index(fields=['driver', 'status'], name='fleet_tripa_driver__34650c_idx'),
        ),
        migrations.AddIndex(
            model_name='tripallocation',
            index=models.Index(fields=['status'], name='fleet_tripa_status_8873d5_idx'),
        ),
        migrations.AddIndex(
            model_name='tripallocation',
            index=models.Index(fields=['created_at'], name='fleet_tripa_created_4fefbc_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', 'service_date'], name='fleet_maint_vehicle_5f7326_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['next_due_date'], name='fleet_maint_next_du_f712ed_idx'),
        ),
    ]
