# Generated by Django 6.0.1 on 2026-02-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripallocation',
            old_name='notes',
            new_name='allocation_notes',
        ),
        migrations.AddField(
            model_name='tripallocation',
            name='actual_departure_datetime',
            field=models.DateTimeField(blank=True, help_text='Actual time when trip started', null=True),
        ),
        migrations.AddField(
            model_name='tripallocation',
            name='actual_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual distance traveled in km', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tripallocation',
            name='actual_return_datetime',
            field=models.DateTimeField(blank=True, help_text='Actual time when trip completed', null=True),
        ),
    ]
