# Generated by Django 6.0.1 on 2026-02-19 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_notificationlog_transport_request_and_more'),
        ('fleet', '0002_rename_notes_tripallocation_allocation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['return_datetime'], name='fleet_trans_return__7cbb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['departure_datetime', 'return_datetime'], name='fleet_trans_departu_dfe101_idx'),
        ),
        migrations.AddIndex(
            model_name='tripallocation',
            index=models.Index(fields=['transport_request', 'status'], name='fleet_tripa_transpo_b207d5_idx'),
        ),
    ]
