# Generated by Django 6.0.1 on 2026-07-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_fill_missing_date_columns_and_indexes'),
        ('bookings', '0002_add_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='activities.activity'),
        ),
    ]
